version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Aron1234!"
      MSSQL_PID: "Express"
    ports:
      - "14330:1433"